// <auto-generated />
using System;
using CampusEcomSystemMini.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusEcomSystemMini.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618

            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // =========================================================
            // BOOK EXCHANGE
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.BookExchangePost", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("BookName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Condition")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("WantedBookName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("Status");

                b.HasIndex("UserId");

                b.ToTable("BookExchangePosts");
            });

            // =========================================================
            // CLAIM
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Claim", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ClaimantUserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("PostId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ClaimantUserId");

                b.HasIndex("PostId");

                b.ToTable("Claims");
            });

            // =========================================================
            // CONNECTION REQUEST - MODULE 5
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.ConnectionRequest", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("ReceiverId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("SenderId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ReceiverId");

                b.HasIndex("SenderId");

                b.ToTable("ConnectionRequests");
            });

            // =========================================================
            // CONVERSATION - MODULE 5
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Conversation", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Conversations");
            });

            // =========================================================
            // CONVERSATION PARTICIPANT - MODULE 5
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.ConversationParticipant", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ConversationId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.HasIndex("ConversationId", "UserId")
                    .IsUnique();

                b.ToTable("ConversationParticipants");
            });

            // =========================================================
            // DOCUMENT - MODULE 4
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Document", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<long>("FileSize")
                    .HasColumnType("bigint");

                b.Property<string>("FileType")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Price")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("PricingType")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<decimal>("Rating")
                    .HasPrecision(3, 2)
                    .HasColumnType("decimal(3,2)");

                b.Property<int>("ReviewCount")
                    .HasColumnType("int");

                b.Property<string>("StoredFileName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Subject")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("PricingType");

                b.HasIndex("UserId");

                b.ToTable("Documents");
            });

            // =========================================================
            // DOCUMENT REVIEW - MODULE 4
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.DocumentReview", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Comment")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("DocumentId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("Rating")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("DocumentId");

                b.HasIndex("UserId");

                b.HasIndex("DocumentId", "UserId")
                    .IsUnique();

                b.ToTable("DocumentReviews");
            });

            // =========================================================
            // LOST & FOUND
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.GamificationPointTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("Change")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GamificationPointTransactions");
                });

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.LostFoundRecord", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<double?>("Lat")
                    .HasColumnType("float");

                b.Property<double?>("Lng")
                    .HasColumnType("float");

                b.Property<string>("Location")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("PostId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Status")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("PostId")
                    .IsUnique();

                b.ToTable("LostFoundRecords");
            });

            // =========================================================
            // MESSAGE - MODULE 5
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Message", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("ConversationId")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("IsRead")
                    .HasColumnType("bit");

                b.Property<Guid>("SenderId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("SentAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ConversationId");

                b.HasIndex("SenderId");

                b.ToTable("Messages");
            });

            // =========================================================
            // NOTIFICATION - MODULE 5
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Notification", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsRead")
                    .HasColumnType("bit");

                b.Property<string>("Message")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("RelatedId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("Notifications");
            });

            // =========================================================
            // POST
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Post", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Type")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("Posts");
            });

            // =========================================================
            // POST LIKE
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.PostLike", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("PostId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.HasIndex("PostId", "UserId")
                    .IsUnique();

                b.ToTable("PostLikes");
            });

            // =========================================================
            // PREFERENCE
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Preference", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Goals")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Habits")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("InterestedSubjects")
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal?>("MonthlyRentalBudget")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("PreferredRentalArea")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserId")
                    .IsUnique();

                b.ToTable("Preferences");
            });

            // =========================================================
            // SECRET QUESTION
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.SecretQuestion", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("PostId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Question")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("SecretAnswerHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("PostId")
                    .IsUnique();

                b.ToTable("SecretQuestions");
            });

            // =========================================================
            // USER
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AvatarUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Phone")
                    .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReputationPoints")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Users");
            });

            // =========================================================
            // RELATIONSHIPS
            // =========================================================
                b.HasKey("Id");

                b.ToTable("Users");
            });

            // =========================================================
            // RELATIONSHIPS
            // =========================================================

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.GamificationPointTransaction", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();
            });

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.LostFoundRecord", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.Post", null)
                    .WithMany()
                    .HasForeignKey("PostId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.BookExchangePost", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Claim", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("ClaimantUserId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.HasOne("CampusEcomSystemMini.Domain.Entities.Post", null)
                    .WithMany()
                    .HasForeignKey("PostId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            // ConnectionRequest
            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.ConnectionRequest", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("ReceiverId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.HasOne("CampusEcomSystemMini.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("SenderId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();
            });

            // ConversationParticipant
            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.ConversationParticipant", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.Conversation", null)
                    .WithMany()
                    .HasForeignKey("ConversationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CampusEcomSystemMini.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();
            });

            // Document
            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Document", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            // DocumentReview
            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.DocumentReview", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.Document", null)
                    .WithMany()
                    .HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CampusEcomSystemMini.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();
            });

            // LostFoundRecord
            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.LostFoundRecord", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.Post", null)
                    .WithMany()
                    .HasForeignKey("PostId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            // Message
            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Message", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.Conversation", null)
                    .WithMany()
                    .HasForeignKey("ConversationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CampusEcomSystemMini.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("SenderId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();
            });

            // Notification
            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Notification", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();
            });

            // Post
            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Post", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            // PostLike
            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.PostLike", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.Post", null)
                    .WithMany()
                    .HasForeignKey("PostId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CampusEcomSystemMini.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();
            });

            // Preference
            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Preference", b =>
                {
                    b.HasOne("CampusEcomSystemMini.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.Report", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.Post", null)
                    .WithMany()
                    .HasForeignKey("PostId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CampusEcomSystemMini.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("ReporterId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();
            });

            // SecretQuestion
            modelBuilder.Entity("CampusEcomSystemMini.Domain.Entities.SecretQuestion", b =>
            {
                b.HasOne("CampusEcomSystemMini.Domain.Entities.Post", null)
                    .WithMany()
                    .HasForeignKey("PostId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

#pragma warning restore 612, 618
        }
    }
}